[project]
name = "nbs-livetable"
dynamic = ["version"]
description = "An implementation of LiveTable running over Kafka or ZMQ"
authors = [
    {name = "Charles Titus", email = "ctitus@bnl.gov"}
]
requires-python = ">=3.8"
keywords = ["bluesky", "nsls-ii", "gui"]
dependencies = [
    "qtpy",
    "bluesky-kafka>=0.10.0",
    "bluesky-widgets>=0.0.16",
    "nslsii",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Public Domain",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research"
]

[project.urls]
homepage = "https://github.com/xraygui/livetable"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[project.scripts]
kafka-livetable = "nbs_livetable.kafka_table:main"
qt-kafka-livetable = "nbs_livetable.QtKafkaTable:main"
zmq-livetable = "nbs_livetable.zmq_table:main"
qt-zmq-livetable = "nbs_livetable.QtZmqTable:main"


[project.entry-points."nbs_gui.tabs"]
kafka-table-tab = "nbs_livetable.QtKafkaTable:QtKafkaTableTab"
zmq-table-tab = "nbs_livetable.QtZmqTable:QtZMQTableTab"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.feature.build.dependencies]
hatch = "*"

[tool.pixi.feature.build.tasks]
build = "hatch build"
test-release = "hatch publish -r test"

[tool.pixi.feature.test.pypi-dependencies]
nbs-livetable = { path=".", editable = true }

[tool.pixi.environments]
build = { features = ["build"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }